### ISSUE TITLE
Cell Format

### ISSUE THREAD

**Issue by dracoraj** [Aymkdn/ExcelPlus#10]
Hi Team,

 I want to change my cell formation like the following, 
 ->colour changing, 
-> Column head style as bold
-> Width size 
Any Method from the ExcelPlus  will support this changes. Please confirm.

Thanks 
Raj
[Test.xlsx](https://github.com/Aymkdn/ExcelPlus/files/816629/Test.xlsx)

**Comment by Aymkdn** [comment]
Hi,

There is no team here, but only me ;-)

ExcelPlus is based on [js-xslx](https://github.com/SheetJS/js-xlsx/) 0.8.0 that doesn't support cell formatting, so ExcelPlus doesn't support cell formatting either.

Recently the [js-xslx](https://github.com/SheetJS/js-xlsx/) has been updated. I'm not sure they now provide the formatting option.... it's something I'll check in the coming days.

**Comment by Aymkdn** [comment]
I've reviewed the last changes for [js-xslx](https://github.com/SheetJS/js-xlsx/) and the style formatting is still not supported.

Another fork of js-xlsx exists and it looks like it works with cell formatting: https://github.com/protobi/js-xlsx

When [js-xslx](https://github.com/SheetJS/js-xlsx/) will support it, then I'll modify ExcelPlus to support it too.

**Comment by Aymkdn** [comment]
This new project https://github.com/dtjohnson/xlsx-populate looks very nice, easy to use and with style support!

**Comment by Aymkdn** [comment]
And here is another project that looks even better: https://github.com/guyonroche/exceljs

**Comment by Aymkdn** [comment]
Project deprecated
