### ISSUE TITLE
Write to an existing excel workbook

### ISSUE THREAD

**Issue by johnothetree** [Aymkdn/ExcelPlus#12]
Is there a way to use ExcelPlus to write a few values to an existing excel workbook? by my current understanding, it would require reading in an existing workbook, modifying it, and then writing, but by the API you have written up, that would only create a new excel workbook with the same name (with a (1) on the end, of course).

**Comment by Aymkdn** [comment]
You cannot interact with an Excel file directly. At least, I don't see how you could from the browser (or with the old ActiveX)... With this lib you'll have to read it, modify what you want and send it back to the user. 

If you use Node maybe it would be possible. See this example : https://github.com/SheetJS/js-xlsx/issues/134#issuecomment-288323169
With Node you might be able to overwrite the existing file.
