### ISSUE TITLE
Support dataURI for openLocal

### ISSUE THREAD

**Issue by natcohen** [Aymkdn/ExcelPlus#13]
It should be possible to pass data directly to the openLocal function to allow more flexibility...

**Comment by Aymkdn** [comment]
Hi,

Can you give more context please? What is your case?

Thanks

**Comment by natcohen** [comment]
Well, I'd like to customize my button... I would like to send myself the data to the library so I can do whatever I want before and after I load the file!

**Comment by Aymkdn** [comment]
I'll see if I can add a `open` only function in a future release.

In the meantime you could do something like that:
```javascript
var ep = new ExcelPlus();
// below is the code to read directly from your file data
ep.oFile = XLSX.read(yourFileData, {type: 'binary', cellDates:true, cellStyles:true});
ep.nbSheets = ep.oFile.SheetNames.length;
if (ep.nbSheets == 1) ep.selectSheet(1);
// and then you can do your normal stuff with ExcelPlus
console.log(ep.read('A1'));
```
For `XLSX.read` you can find the options there: https://github.com/SheetJS/js-xlsx#parsing-options
You may need to change the `type` depending of the kind of data you passed to the function.

**Comment by natcohen** [comment]
@Aymkdn Will try that later... however, this should definitely be supported! I'm even surprised of this type of implementation.

**Comment by Aymkdn** [comment]
At first I built this library for me, because the `js-xlsx` was complicated to use directly. And I didn't need to use this kind of function so far :-)

**Comment by natcohen** [comment]
@Aymkdn I see... your library is so complete that it doesn't look like a personal project! Good job and thanks for sharing your work

**Comment by reviewher** [comment]
@natcohen if you need to support data URI, you can parse the string:

```js
var header = dataURI.substr(0, dataURI.indexOf(","));
var data = dataURI.substr(dataURI.indexOf(","));
var type = header.match(/;base64/) ? "base64" : "binary";
XLSX.read(data, {type:type, ...})
```

@Aymkdn should we add a dataURI mode to js-xlsx or add the functionality here?

**Comment by Aymkdn** [comment]
@reviewher I don't manage js-xlsx, so feel free to open an issue or a pull request there! They are very responsive lately.

**Comment by natcohen** [comment]
@reviewher Actually I just want to have a custom function when I upload the file and a custom design

**Comment by Aymkdn** [comment]
Function `open()` added with the new release v2.5
