### ISSUE TITLE
Deleting last row will return a null row

### ISSUE THREAD

**Issue by natcohen** [Aymkdn/ExcelPlus#15]
Not sure if it's a bug or by design but if you have an excel file and you remove the last row, `readAll` will return a table with the last row being a serie of null while it shouldn't return the row at all (IMHO)...

**Comment by Aymkdn** [comment]
Hi,

I think this is related to `js-xlsx` and not to this project (ExcelPlus is a layer on top of `js-xlsx`). When I have time I'll run some tests about it.

**Comment by Aymkdn** [comment]
Project deprecated
