### ISSUE TITLE
I get an error in the browser. It is telling me that excelplus-2.5.min.js is not found

### ISSUE THREAD

**Issue by zavakare** [Aymkdn/ExcelPlus#17]
I get an error in the browser. It is telling me that excelplus-2.5.min.js is not found
![image](https://cloud.githubusercontent.com/assets/16713500/25240280/07b4bd60-25b8-11e7-9184-4ef058a28b81.png)

**Comment by Aymkdn** [comment]
You obviously need to download the file and put it on your server....

**Comment by zavakare** [comment]
@Aymkdn  Thank you so much!
