### ISSUE TITLE
excelplus Issue

### ISSUE THREAD

**Issue by zavakare** [Aymkdn/ExcelPlus#18]
I get an error in the browser. It is telling me that excelplus-2.5.min.js is not found
![image](https://cloud.githubusercontent.com/assets/16713500/25240280/07b4bd60-25b8-11e7-9184-4ef058a28b81.png)

**Comment by Aymkdn** [comment]
Duplicate

**Comment by zavakare** [comment]
@Aymkdn  Quick question , should this be able to open the excel file created? I am not able to open it.
Is there a way to switch the type of file to .xls instead of .xlsx?
