### ISSUE TITLE
export xls with a image

### ISSUE THREAD

**Issue by oreillyj1** [Aymkdn/ExcelPlus#19]
Hi does this library allow me to export a xls with a image somewhere on the sheet? if there are any jsfiddles on the web showing this it would also be great..
thanks
James

**Comment by Aymkdn** [comment]
See https://github.com/SheetJS/js-xlsx/issues/642

**Comment by oreillyj1** [comment]
hi Aymkdn, so  SheetJS/js-xlsx allows images to be included in the export? thanks

**Comment by Aymkdn** [comment]
@oreillyj1 > I don't know. I closed this issue because it depends of js-xlsx, and not of ExcelPlus. Your question has to be treated by the people behind js-xlsx.

**Comment by oreillyj1** [comment]
oh ok, I though ExcelPlus might have the image option. I'll go and look around  js-xlsx thanks

**Comment by Aymkdn** [comment]
ExcelPlus uses js-xlsx. It's just an interface to make things easier to deal with js-xlsx! So if something is not available with js-xlsx it won't be available with ExcelPlus either.
