### ISSUE TITLE
add styles to cell

### ISSUE THREAD

**Issue by shijuabraham** [Aymkdn/ExcelPlus#2]
Is there a way we can add styles to individual cells or entire rows?

**Comment by Aymkdn** [comment]
Hi,

No... because it's based on https://github.com/SheetJS/js-xlsx/ and this project doesn't include an easy way to manage the style. 

If you need style, you can try this fork of js-xlsx : https://github.com/protobi/js-xlsx

**Comment by Aymkdn** [comment]
BTW, it's something I want to add at some point... I just don't have the time right now :-/

**Comment by shijuabraham** [comment]
Thanks. Will check out js-xlsx.

**Comment by StillOnMyWay** [comment]
Any update on this?

**Comment by Aymkdn** [comment]
@StillOnMyWay : not on my side. It's time consuming and I didn't find the bandwidth to try something. So if you need that option you can give it a try with https://github.com/protobi/js-xlsx !
