### ISSUE TITLE
How to use style 

### ISSUE THREAD

**Issue by pleger** [Aymkdn/ExcelPlus#21]
Hi, In the first place, thanks a lot for your work.

I am using ExcelPlus and I cannot give a simple style to Cell (or row). For example, I would like that the header cells (first row) are bold and centered. Can you write one or a few lines for that? I guess something like

ep.writeCell("DATA", {bold:true, centered: true}); 
//or 
ep.writeRow(content, {bold:true, centered: true});

In addition, Is possible to give a style to a column? For example, wrap text?

ep.columStyle("A", {wrapText: true});

Thanks in advance, Paul

**Comment by Aymkdn** [comment]
Hi 

Please refer to https://github.com/Aymkdn/ExcelPlus/issues/10
