### ISSUE TITLE
not able to create sheet of name in number like 100,200....etc, 

### ISSUE THREAD

**Issue by sundar9511** [Aymkdn/ExcelPlus#23]

**Comment by Aymkdn** [comment]
No code provided, no details, nothing.... I close this issue. Please be more specific !

Also ExcelPlus is just an interface for [js-xslx](https://github.com/SheetJS/js-xlsx/). If something doesn't work with `js-xlsx` then it won't work with ExcelPlus either.

Finally, please check other projects like https://github.com/dtjohnson/xlsx-populate or https://github.com/guyonroche/exceljs
