### ISSUE TITLE
Cannot import script in Web Worker

### ISSUE THREAD

**Issue by Jibodeah** [Aymkdn/ExcelPlus#24]
I tried to import the script from within a web worker and it throws errors.

[Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API) do not have a window object, they have a `self` instead. So it's fairly common to patch this up for scripts that expect `window` to exist by setting `var window = self`. But even with this the script still fails to load.

The traceback leads to the obfuscated saveAs function. The specific error being `TypeError: r is undefined`

...As one might imagine being able to use this script from within a web worker would be quite useful as one does not have to lock up the main thread while generating a big spreadsheet, for example.

**Comment by Aymkdn** [comment]
Please see the comments there : https://github.com/Aymkdn/ExcelPlus/issues/10
