### ISSUE TITLE
addEventListener overlap with Google Maps Javascript V3

### ISSUE THREAD

**Issue by tvoloshyn** [Aymkdn/ExcelPlus#3]
Dear @Aymkdn,

Looks like there is an overlap between **Google Maps JavaScript V3** and **ExcelPlus** when it comes to declaration of `addEventListener` polyfill.

When I include your library with google maps library, markers and the map itself looses drag functionality.
I've tried renaming `addEventListener` function and replacing it where it is being used and this has solved my issue.

Regards,
Taras

**Comment by Aymkdn** [comment]
OK, thank you to let me know. I'll change it for a future release !
