### ISSUE TITLE
Cell Formatting

### ISSUE THREAD

**Issue by jpeacock76179** [Aymkdn/ExcelPlus#5]
Is it possible for the cell data to be formatted as a date or a number. Right now, everything is a text. Thanks.

**Comment by Aymkdn** [comment]
You have to pass a Date object, in the `write()` and then it will be shown as a date in your sheet.

**Comment by jpeacock76179** [comment]
Thanks for the quick response.
I see that now if I had looked closer at the examples. My current code is using the writeNextRow(). Is it possible with that function? If not, I can convert to the write().

**Comment by jpeacock76179** [comment]
Nevermind. I got the Date object to work with the writeNextRow. THanks.
