### ISSUE TITLE
Getting an error when trying to write numbers

### ISSUE THREAD

**Issue by natcohen** [Aymkdn/ExcelPlus#6]
I'm using the last version 2.4.1 and whenever I tri to do `excel.write({"cell": "A1" ,"content":  0});` I'm getting the following error: `[ExcelPlus] [write] Please provide the 'content'`.

The problem disappears when I write `"0"` instead of `0`...

**Comment by Aymkdn** [comment]
It's actually because the test is `if (!options.content) {` and with `0` it valids it.... You can replace [this line](https://github.com/Aymkdn/ExcelPlus/blob/master/2.4.1/excelplus-2.4.1.js#L482) with `if (options.content === undefined) {`

**Comment by natcohen** [comment]
This is a bug and should be fixed in future releases...
