### ISSUE TITLE
Can't get line break inside a cell

### ISSUE THREAD

**Issue by natcohen** [Aymkdn/ExcelPlus#7]
I have tried to add `\n` and `\r\n` without success is there a way to have a line break?

**Comment by Aymkdn** [comment]
I think you need to use a special character (not `\n` or \r\n`). Try searching on Google. I cannot test or search right now. I'll have a look at it on tomorrow.

**Comment by natcohen** [comment]
Thanks, I've found that adding `CHAR(10)` in a formula does the trick

**Comment by natcohen** [comment]
Reopening this because `CHAR(10)` requires the cell to be recognized by Excel as a formula and by writing this: `content: '="Hello " & CHAR(10) & "World"'` Excel considers the cell as being a string. Hence the line break is displayed only if you go inside the cell and leave it.

**Comment by Aymkdn** [comment]
ExcelPlus is an interface for https://github.com/SheetJS/js-xlsx

I think this problem is due to that library, so you can try to search for a solution there. If you find something, please let me know.

**Comment by Aymkdn** [comment]
Project deprecated
